server {
	listen 8080;
	listen [::]:8080;
	server_name _;
	root /usr/share/nginx/html;
	charset utf-8;

	gzip on;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss image/svg+xml;

	location / {
		try_files $uri $uri/ /index.html;
	}
}
